version: "3"
services:

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d/app.template:/etc/nginx/conf.d/app.template
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/app.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"

  app:
    build: .
    container_name: app
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongo
      - mysql

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - '27017:27017'
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=secret
#      - MONGO_INITDB_DATABASE=nodedb

  mysql:
    image: mysql:5.7
    hostname: "mysql"
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_OUTER_PORT}:${MYSQL_INNER_PORT}"
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  data-volume:
